// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfOHRi_wVbrIWjxa060dO2wuvKoCA-LbY',
    appId: '1:915343870241:web:00ada56f70a658a719d660',
    messagingSenderId: '915343870241',
    projectId: 'ensa-campus',
    authDomain: 'ensa-campus.firebaseapp.com',
    storageBucket: 'ensa-campus.appspot.com',
    measurementId: 'G-5E93836C4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_y4wjjOlqniHd1xKRy3EF2QLF_Zqchn4',
    appId: '1:915343870241:android:4f6549f1cce4be3e19d660',
    messagingSenderId: '915343870241',
    projectId: 'ensa-campus',
    storageBucket: 'ensa-campus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn2Horwk7ZqDM81xJL37AmlFjzzumutIs',
    appId: '1:915343870241:ios:9a782f4ce9a3955b19d660',
    messagingSenderId: '915343870241',
    projectId: 'ensa-campus',
    storageBucket: 'ensa-campus.appspot.com',
    iosBundleId: 'com.example.ensaCampus',
  );
}
